[font]
size = 9

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "PasteSelection" }]

[colors.primary]
# background = "#000000"
# foreground = "#ffffff"

[selection]
save_to_clipboard = true
